### ISSUE TITLE
Recoverable Fatal error with Database Backend

### ISSUE THREAD

**Issue by zuhairkareem** [dawehner/search_api_autocomplete#1]
I get the following error as Ajax Response for search api autocomplete with database backend.

![search_autocomplete](https://cloud.githubusercontent.com/assets/4180013/17506086/9f4f31b2-5e23-11e6-920a-8de1fdcbaf67.png)

**Comment by dawehner** [comment]
@zuhairkareem 
Did you applied the patch to search_api itself as well? https://www.drupal.org/node/2747283#comment-11483771

**Comment by zuhairkareem** [comment]
@dawehner I am using the 8.x-1.0-alpha16 version of Search API. Therefore patch doesn't apply. When I updated Search API to dev version to apply the patch, i get the errors discussed over here : https://www.drupal.org/node/2776711 . I think it is not completely solved right now and therefore i am kind of stuck :|

**Comment by dawehner** [comment]
Well, you know, at least there is some form of search_api_autocomplete
available :)
Did you tried to disable facetapi and see whether search_api_autocomplete
for itself works?

**Comment by zuhairkareem** [comment]
@dawehner So I installed Search API dev version and Search API autocomplete in a clean D8 install  without facets module and setup an index with DB backend. Then i applied the patch you mentioned first to Search API dev module. And still i get the following 500 error on autocomplete - 

`Uncaught PHP Exception Drupal\\Core\\Database\\DatabaseExceptionWrapper: "SQLSTATE[42000]: Syntax error or access violation: 1463 Non-grouping field 'results' is used in HAVING clause: SELECT t.word AS word, COUNT(DISTINCT item_id) AS results\nFROM \n(SELECT t.word AS word, t.item_id AS item_id\nFROM \n{search_api_db_test_text} t\nWHERE  (item_id IN  (:db_condition_placeholder_0, :db_condition_placeholder_1, :db_condition_placeholder_2, :db_condition_placeholder_3, :db_condition_placeholder_4, :db_condition_placeholder_5, :db_condition_placeholder_6, :db_condition_placeholder_7, :db_condition_placeholder_8, :db_condition_placeholder_9, :db_condition_placeholder_10, :db_condition_placeholder_11, :db_condition_placeholder_12, :db_condition_placeholder_13, :db_condition_placeholder_14, :db_condition_placeholder_15, :db_condition_placeholder_16, :db_condition_placeholder_17, :db_condition_placeholder_18, .....`

**Comment by dawehner** [comment]
Interesting, I haven't seen that one yet :)

**Comment by zuhairkareem** [comment]
@dawehner Ouch :) ..This is screenshot from recent log message - 
![test](https://cloud.githubusercontent.com/assets/4180013/17514215/f43cc6be-5e4e-11e6-985e-88af00e4db28.png)

**Comment by zuhairkareem** [comment]
I have added an issue in search api about this error and a simple patch - https://www.drupal.org/node/2783987 . 

I have another error with results returned 

`Error: Call to a member function getUrl() on array in Drupal\search_api_autocomplete\Controller\AutocompleteController->autocomplete() (line 91 of /var/www/html/drupal8/modules/contrib/search modules/search_api_autocomplete/src/Controller/AutocompleteController.php).`

It is expecting an object where as an array is returned from getAutocompleteSuggestions in /search_api_db/src/Plugin/search_api/backend/Database.php . 

Why is there a check for URL there?

**Comment by dawehner** [comment]
Let's deal with that on drupal.org :)
